dataset:
  desc: Dataset name
  value: srst19
epoch:
  desc: Number of epochs to train over
  value: 300
batch_size:
  desc: Size of each mini-batch
  value: 1024
regularization:
  desc: Importance of the kernel regualarization term
  value: 0.0001
feature_activation:
  desc: Sigmoid or tanh I guess
  value: sigmoid
learning_rate:
  desc: lr
  value: 0.001
hidden_layers:
  desc: array specifying the number of neurons per layer
  value: [50, 20, 1]