program: main.py
method: bayes
metric:
  goal: maximize
  name: tau_mean_validation
parameters:
  dataset:
    values: 
      - hvr/es_ancora-ud
  feature_activation:
    values:
      - sigmoid
      - relu
    distribution: categorical
  regularization:
    max: 0.0001
    min: 0.00001
    distribution: uniform
  learning_rate:
    max: 0.0001
    min: 0.000005
    distribution: uniform
  epoch:
    values: [60]
    distribution: categorical
  hidden_layers:
    values: [[100,50],[150,100],[150], [100]]
    distribution: categorical
  limit_dataset_size:
    values: [50000]